/* eslint-disable @next/next/no-img-element */
import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { Carousel } from '../components/Carousel';

const elementWidth = 600

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Carousel</h1>
        <Carousel elementWidth={elementWidth}>
          {[1, 2, 3, 4, 5].map((index) => {
            return (
              <img src={"/dummy-600-400.png"} alt="dummy image" width={elementWidth} key={index.toString()} />
            )
          })}
        </Carousel>
      </main>
    </div>
  )
}

export default Home
